server:
  port: 8080

spring:
  datasource:
    driver-class-name: software.amazon.jdbc.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect # Opcional, pero recomendado